# Generated by Django 3.1.4 on 2020-12-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_auto_20201209_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
