# Generated by Django 3.1.4 on 2020-12-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_auto_20201209_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='child_care_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='budget',
            name='food_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='budget',
            name='medical_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='budget',
            name='taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='budget',
            name='earned_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='budget',
            name='housing_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
